### ISSUE TITLE
Templates not compiling correctly?

### ISSUE THREAD

**Issue by patrickml** [timbrandin/meteor-react-jsx-templating#2]
For some reason my templates are being complied into react elements?

I have this template named like `main.html.jsx`

and the code looks like this

~~~
<template name="MainTemplate">
  <div class="main-container">

  </div>
</template>
~~~

but when it compiles I am seeing the following

~~~
(function(){React.createElement(
  "template",
  { name: "MainTemplate" },
  React.createElement("div", { "class": "main-container" })
);

})();
~~~

any idea?

I added `react` to my project in order to use `FlowRouter` with react components

**Comment by timbrandin** [comment]
That's odd, there should a getMeteorData in there too and some more things. Not sure what is happening. What else is in your app?

**Comment by patrickml** [comment]
Nothing it was a brand new meteor app i was trying to test out React + Meteor and your compiler is obviously the best choice when it comes to starting out. But my router.jsx wouldnt compile unless i added meteor react

**Comment by timbrandin** [comment]
See how I've done it:
https://github.com/SpaceTalk/SpaceTalk-Homepage
https://github.com/timbrandin/meteor-iosmorphic-react-templating
https://github.com/timbrandin/resumeteor

Maybe it'll help?

**Comment by patrickml** [comment]
So it seems like it helped

~~~
(function(){
var Template = Template || {};
Template.MainTemplate = {
  onCreated: function (f) {
    return this._onCreated = f || (this._onCreated || function () {});
  },
  helpers: function (o) {
    return this._helpers = o || (this._helpers || {});
  } };
MainTemplate = React.createClass({ displayName: "MainTemplate",
  _created: false,
  mixins: [ReactMeteorData],
  getMeteorData: function () {
    var self = this;
    if (!self._created) {
      Tracker.nonreactive(function () {
        Template.MainTemplate.onCreated().call(self);
      });
      self._created = true;
    }
    var _helpers = {};
    var helpers = Template.MainTemplate.helpers();
    for (var key in helpers) {
      _helpers[key] = helpers[key].call(self);
    };
    return _helpers;
  },
  render: function () {
    return React.createElement(
      "div",
      { className: "main-container" },
      this.props.navTemplate,
      React.createElement(
        "div",
        { className: "body-container" },
        this.props.bodyTemplate,
        this.props.footerTemplate
      )
    );
  }
});

})();

~~~

But i am still receiving an error in flow router stating that MainTemplate doesnt exist... any ideas?

**Comment by patrickml** [comment]
@timbrandin I figured it out. I was using the traditional `/client` for my templates so the code wasn't on the server (figures)

**Comment by patrickml** [comment]
@timbrandin how far off do you think template events are?

**Comment by timbrandin** [comment]
They're 90% done, just need to get them stitched onto the React component
on the correct place with the correct event, though I'm not sure how to
best capture the this (context) with all data, which is a super-useful
thing in Meteor's Blaze.


2015-07-14 4:39 GMT+02:00 Patrick Lewis <notifications@github.com>:

> @timbrandin <https://github.com/timbrandin> how far off do you think
> template events are?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timbrandin/meteor-react-jsx-templating/issues/2#issuecomment-121115455>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by patrickml** [comment]
Within the on click of the element call .bind(null, this)

**Comment by timbrandin** [comment]
Great, perfect! Thx! // T

2015-07-14 14:51 GMT+02:00 Patrick Lewis <notifications@github.com>:

> Within the on click of the element call .bind(null, this)
> On Tue, Jul 14, 2015 at 2:54 AM Tim Brandin <notifications@github.com>
> wrote:
>
> > They're 90% done, just need to get them stitched onto the React component
> > on the correct place with the correct event, though I'm not sure how to
> > best capture the this (context) with all data, which is a super-useful
> > thing in Meteor's Blaze.
> >
> >
> > 2015-07-14 4:39 GMT+02:00 Patrick Lewis <notifications@github.com>:
> >
> > > @timbrandin <https://github.com/timbrandin> how far off do you think
> > > template events are?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/timbrandin/meteor-react-jsx-templating/issues/2#issuecomment-121115455
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Cheers,
> > // Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
> > http://timbrandin.com
> > http://studiointeract.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/timbrandin/meteor-react-jsx-templating/issues/2#issuecomment-121147414
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timbrandin/meteor-react-jsx-templating/issues/2#issuecomment-121230088>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com
